### ISSUE TITLE
What do hashOP, pow3, pow7 and fact6 mean?

### ISSUE THREAD

**Issue by sparklingyueran** [MeepMoop/py222#1]
hashOP = np.array([1, 2, 10])
pow3 = np.array([1, 3, 9, 27, 81, 243, 729])
pow7 = np.array([1, 7, 49, 343, 2401, 16807, 117649])
fact6 = np.array([720, 120, 24, 6, 2, 1, 1])

**Comment by MeepMoop** [comment]
These are all arrays for converting a state (or portions of the state) into unique indices. hashOP is used to convert a set of 3 stickers (in a particular order) into an index which captures what piece it is, as well as its orientation. pow3 is used to get a unique index for the orientations of the state's pieces, and pow7 is used to get a unique index for the permutation of the state's pieces. fact6 is also to get a much more compact unique index (smaller indices) for the permutation of the state's pieces, but it takes longer to compute than the one which uses pow7. :)
